<?php
$users = array(
	array(
		"id" => 1,
		"firstName" => "Adamo",
		"lastName" => "ROSSI",
		"email" => "adamo.rossi@email.com",
		"birthday" => "2002-06-12",
	),
	array(
		"id" => 2,
		"firstName" => "Mario",
		"lastName" => "FERRARI",
		"email" => "mario.ferrari@email.com",
		"birthday" => "2001-06-12",
	),
	array(
		"id" => 3,
		"firstName" => "Luigi",
		"lastName" => "RUSSO",
		"email" => "luigi.russo@email.com",
		"birthday" => "2007-08-06",
	),
	array(
		"id" => 4,
		"firstName" => "Achille",
		"lastName" => "BIANCHI",
		"email" => "achille.bianchi@email.com",
		"birthday" => "2006-03-14",
	),
	array(
		"id" => 5,
		"firstName" => "Adriano",
		"lastName" => "ROMANO",
		"email" => "adriano.romano@email.com",
		"birthday" => "2005-01-16",
	),
	array(
		"id" => 6,
		"firstName" => "Gianni",
		"lastName" => "ROSSI",
		"email" => "gianni.rossi@email.com",
		"birthday" => "2005-04-22",
	),
	array(
		"id" => 7,
		"firstName" => "Giuliano",
		"lastName" => "FERRARI",
		"email" => "giuliano.ferrari@email.com",
		"birthday" => "2007-07-16",
	),
	array(
		"id" => 8,
		"firstName" => "Giusto",
		"lastName" => "RUSSO",
		"email" => "giusto.russo@email.com",
		"birthday" => "2001-03-28",
	),
	array(
		"id" => 9,
		"firstName" => "Livio",
		"lastName" => "BIANCHI",
		"email" => "livio.bianchi@email.com",
		"birthday" => "2003-01-19",
	),
	array(
		"id" => 10,
		"firstName" => "Paolo",
		"lastName" => "ROMANO",
		"email" => "paolo.romano@email.com",
		"birthday" => "2001-09-28",
	),
	array(
		"id" => 11,
		"firstName" => "Onorato",
		"lastName" => "ROSSI",
		"email" => "onorato.rossi@email.com",
		"birthday" => "2005-06-29",
	),
	array(
		"id" => 12,
		"firstName" => "Silvio",
		"lastName" => "FERRARI",
		"email" => "silvio.ferrari@email.com",
		"birthday" => "2005-04-11",
	),
	array(
		"id" => 13,
		"firstName" => "Tancredi",
		"lastName" => "RUSSO",
		"email" => "tancredi.russo@email.com",
		"birthday" => "2000-07-30",
	),
	array(
		"id" => 14,
		"firstName" => "Valter",
		"lastName" => "BIANCHI",
		"email" => "valter.bianchi@email.com",
		"birthday" => "2000-06-10",
	),
	array(
		"id" => 15,
		"firstName" => "Zeno",
		"lastName" => "ROMANO",
		"email" => "zeno.romano@email.com",
		"birthday" => "2001-07-21",
	),
	array(
		"id" => 16,
		"firstName" => "Adamo",
		"lastName" => "ROSSI",
		"email" => "adamo.rossi@email.com",
		"birthday" => "2007-07-18",
	),
	array(
		"id" => 17,
		"firstName" => "Mario",
		"lastName" => "FERRARI",
		"email" => "mario.ferrari@email.com",
		"birthday" => "2000-08-15",
	),
	array(
		"id" => 18,
		"firstName" => "Luigi",
		"lastName" => "RUSSO",
		"email" => "luigi.russo@email.com",
		"birthday" => "2003-10-15",
	),
	array(
		"id" => 19,
		"firstName" => "Achille",
		"lastName" => "BIANCHI",
		"email" => "achille.bianchi@email.com",
		"birthday" => "2000-05-08",
	),
	array(
		"id" => 20,
		"firstName" => "Adriano",
		"lastName" => "ROMANO",
		"email" => "adriano.romano@email.com",
		"birthday" => "2007-04-23",
	),
);

return $users;